Repository Soongsil-CoffeeChat/COGO-DEV-server, pull requests merged in 2024-11, with the labels that each got.

#174 refactor: 가능시간 조회 기간 2주로 설정
  src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java
Labels: :recycle: refactor

#181 FIX: User 역할에 따른 Application 조회 로직 간소화
  src/main/java/com/soongsil/CoffeeChat/entity/User.java
  src/main/java/com/soongsil/CoffeeChat/repository/ApplicationRepository.java
  src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
Labels: :bug: fix

#185 feat: 토큰 기반 멘토 가능 시간 조회 API 구현
  src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java
  src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java
Labels: :sparkles: feat

#188 REFACTOR: COGO 신청 로직 변경
  src/main/java/com/soongsil/CoffeeChat/aspect/ApplicationCleanupAspect.java
  src/main/java/com/soongsil/CoffeeChat/controller/handler/ApplicationExceptionHandler.java
  src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateGetResponseDto.java
  src/main/java/com/soongsil/CoffeeChat/entity/Application.java
  src/main/java/com/soongsil/CoffeeChat/entity/PossibleDate.java
  src/main/java/com/soongsil/CoffeeChat/repository/ApplicationRepository.java
  src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepository.java
  src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepositoryImpl.java
  src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
  src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java
  src/main/resources/application.yml
Labels: :sparkles: feat, :recycle: refactor

#190 REFACTOR: 파트별 멘토 리스트 조회, 멘토 상세 정보 조회 토큰 해제
  src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
  src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
Labels: :recycle: refactor
