Repository Soongsil-CoffeeChat/COGO-DEV-server, pull requests merged in 2024-12, with the labels that each got.

#192 [FEAT] 모바일용 토큰 재발급 API
  src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
  src/main/java/com/soongsil/CoffeeChat/controller/RefreshTokenController.java
  src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java
  src/main/java/com/soongsil/CoffeeChat/service/RefreshTokenService.java
Labels: :sparkles: feat, :recycle: refactor

#194 feat: 모바일 토큰 발급 시 신규 계정 여부 추가
  src/main/java/com/soongsil/CoffeeChat/controller/RefreshTokenController.java
  src/main/java/com/soongsil/CoffeeChat/dto/MobileTokenResponseDTO.java
  src/main/java/com/soongsil/CoffeeChat/dto/Oauth/MobileUserDTO.java
  src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java
Labels: :sparkles: feat

#195 fix: 모바일 토큰 발급 시 신규 계정 여부 추가 에러
  src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
  src/main/java/com/soongsil/CoffeeChat/dto/MobileTokenResponseDTO.java
  src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepository.java
  src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java
Labels: :bug: fix, :sparkles: feat

#199 bug: 모바일 인증 로직 수정
  src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java
  src/main/java/com/soongsil/CoffeeChat/service/UserService.java
Labels: :bug: fix

#201 feat: 토큰으로 멘토 자기소개 조회
  src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
  src/main/java/com/soongsil/CoffeeChat/dto/MentorIntroductionGetUpdateResponseDto.java
  src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
Labels: :bug: fix
