Repository Soongsil-CoffeeChat/COGO-DEV-server, pull requests merged in 2024-09, with the labels that each got.

#144 feat: mobile 전용 accessToken 발급 api 구현
  src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
  src/main/java/com/soongsil/CoffeeChat/config/jwt/JWTFilter.java
  src/main/java/com/soongsil/CoffeeChat/controller/RefreshTokenController.java
  src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/RefreshErrorCode.java
  src/main/java/com/soongsil/CoffeeChat/service/CustomOAuth2UserService.java
Labels: :sparkles: feat

#150 refactor: 가능 시간 reqeust dto list형식으로 변환
  src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java
Labels: :recycle: refactor

#152 refactor: 날짜 형식 포맷팅
  src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateResponseDto.java
  src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateGetResponseDto.java
  src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateRequestDto.java
Labels: :recycle: refactor

#154 fix: POST -> PUT
  src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java
Labels: :bug: fix

#157 [REFACTOR] 개인정보 조회 DTO 필드명 변경 및 추가
  src/main/java/com/soongsil/CoffeeChat/dto/UserGetUpdateDto.java
  src/main/java/com/soongsil/CoffeeChat/repository/User/UserRepositoryImpl.java
Labels: :recycle: refactor

#158 refactor: 가능시간 갱신
  src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java
  src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepository.java
  src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java
Labels: :recycle: refactor

#160 refactor: COGO 조회 response dto 수정
  src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java
  src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateResponseDto.java
  src/main/java/com/soongsil/CoffeeChat/dto/ApplicationGetResponseDto.java
  src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateGetResponseDto.java
  src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateRequestDto.java
  src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
  src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java
Labels: :recycle: refactor

#162 fix: cors err security config
  src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
Labels: :bug: fix

#164 fix: 경로에 정규표현식 추가
  src/main/java/com/soongsil/CoffeeChat/config/SecurityConfig.java
Labels: :bug: fix
