Repository Soongsil-CoffeeChat/COGO-DEV-server, pull requests merged in 2024-08, with the labels that each got.

#92 feat: 멘토 상세 정보 조회 API 개발
  .github/ISSUE_TEMPLATE/♻️--refactor-.md
  .github/ISSUE_TEMPLATE/✨--feat--.md
  .github/ISSUE_TEMPLATE/🐛--bug-.md
  .github/ISSUE_TEMPLATE/💚--ci-.md
  src/main/java/com/soongsil/CoffeeChat/controller/Exception/CustomException.java
  src/main/java/com/soongsil/CoffeeChat/controller/Exception/enums/MentorErrorCode.java
  src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
  src/main/java/com/soongsil/CoffeeChat/dto/MentorDto.java
  src/main/java/com/soongsil/CoffeeChat/dto/ResponseMentorInfo.java
  src/main/java/com/soongsil/CoffeeChat/entity/Introduction.java
  src/main/java/com/soongsil/CoffeeChat/entity/Mentor.java
  src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
Labels: :sparkles: feat

#94 refactor: mentorId 기반 서칭으로 리팩토링
  src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
  src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepository.java
  src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
Labels: :sparkles: feat, :recycle: refactor

#96 feat: COGO 관련 로직
  src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
  src/main/java/com/soongsil/CoffeeChat/controller/exception/CustomException.java
  src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/ApplicationErrorCode.java
  src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/MentorErrorCode.java
  src/main/java/com/soongsil/CoffeeChat/controller/exception/enums/PossibleDateErrorCode.java
  src/main/java/com/soongsil/CoffeeChat/dto/ApplicationCreateRequest.java
  src/main/java/com/soongsil/CoffeeChat/dto/ApplicationGetResponse.java
  src/main/java/com/soongsil/CoffeeChat/entity/Application.java
  src/main/java/com/soongsil/CoffeeChat/entity/Mentee.java
  src/main/java/com/soongsil/CoffeeChat/enums/RequestUri.java
  src/main/java/com/soongsil/CoffeeChat/repository/ApplicationRepository.java
  src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
  src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
  src/test/java/com/soongsil/CoffeeChat/Concurrency/ConcurrencyTest.java
Labels: :sparkles: feat, :recycle: refactor

#98 feat: 멘토 세부 정보 수정
  src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
  src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
  src/main/java/com/soongsil/CoffeeChat/dto/MentorUpdateRequestDto.java
  src/main/java/com/soongsil/CoffeeChat/entity/User.java
  src/main/java/com/soongsil/CoffeeChat/repository/Mentor/MentorRepositoryImpl.java
  src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
  src/test/java/com/soongsil/CoffeeChat/QueryTest/GetMentorListTest.java
Labels: :sparkles: feat

#103 Ref/#101 API 전체 점검 후 TODO 작성
  application.log
  src/main/java/com/soongsil/CoffeeChat/controller/ApplicationController.java
  src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
  src/main/java/com/soongsil/CoffeeChat/controller/UserController.java
  src/main/java/com/soongsil/CoffeeChat/dto/ApplicationGetResponse.java
  src/main/java/com/soongsil/CoffeeChat/dto/ChangeUserInfoDto.java
  src/main/java/com/soongsil/CoffeeChat/dto/ResponseMentorInfo.java
  src/main/java/com/soongsil/CoffeeChat/dto/ResponseMentorListInfo.java
  src/main/java/com/soongsil/CoffeeChat/enums/RequestUri.java
  src/main/java/com/soongsil/CoffeeChat/repository/ApplicationRepository.java
  src/main/java/com/soongsil/CoffeeChat/repository/Mentor/MentorRepository.java
  src/main/java/com/soongsil/CoffeeChat/repository/Mentor/MentorRepositoryCustom.java
  src/main/java/com/soongsil/CoffeeChat/repository/Mentor/MentorRepositoryImpl.java
  src/main/java/com/soongsil/CoffeeChat/service/ApplicationService.java
  src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
  src/main/resources/application.yml
  src/test/java/com/soongsil/CoffeeChat/Concurrency/ConcurrencyTest.java
Labels: :recycle: refactor

#109 fix: 가능시간 생성, 조회 디버깅
  src/main/java/com/soongsil/CoffeeChat/controller/MentorController.java
  src/main/java/com/soongsil/CoffeeChat/controller/PossibleDateController.java
  src/main/java/com/soongsil/CoffeeChat/controller/RefreshTokenController.java
  src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateGetDto.java
  src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateGetResponseDto.java
  src/main/java/com/soongsil/CoffeeChat/dto/PossibleDateCreateRequestDto.java
  src/main/java/com/soongsil/CoffeeChat/entity/PossibleDate.java
  src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepository.java
  src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepositoryCustom.java
  src/main/java/com/soongsil/CoffeeChat/repository/PossibleDate/PossibleDateRepositoryImpl.java
  src/main/java/com/soongsil/CoffeeChat/service/MentorService.java
  src/main/java/com/soongsil/CoffeeChat/service/PossibleDateService.java
Labels: :bug: fix

#135 [Feat] 메일 전송 요청시 SQS에 메시지 전달 로직 추가
  src/main/java/com/soongsil/CoffeeChat/config/aws/SqsConfig.java
  src/main/java/com/soongsil/CoffeeChat/config/oauth2/CustomSuccessHandler.java
  src/main/java/com/soongsil/CoffeeChat/util/email/EmailMessage.java
  src/main/java/com/soongsil/CoffeeChat/util/email/EmailUtil.java
  src/main/resources/application.yml
Labels: :sparkles: feat
